# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/hanneshapke/kiji-proxy/discussions/new/choose
    about: To request a feature, open a new discussion under one of the appropriate categories.
  # - name: Our Slack community
  #   url: Slack Link
  #   about: Join our Slack channel for real-time discussion and user support.
